//
//  TOAdvertANE.h
//  TopOnSDK
//
//  Created by 洋吴 on 2019/5/14.
//  Copyright © 2019 洋吴. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "TOAdvertANEUtils.h"
#import "TOFunctions.h"

FREContext TopOnANEEventContext;


#pragma mark - sdk
TOPON_ANE_FUNCTION(SDK_INIT);
TOPON_ANE_FUNCTION(SDK_VERSION);

#pragma mark - video
TOPON_ANE_FUNCTION(TO_VIDEO_START);
TOPON_ANE_FUNCTION(TO_VIDEO_IS_READY);
TOPON_ANE_FUNCTION(TO_VIDEO_SHOW);

#pragma mark - interstitial

TOPON_ANE_FUNCTION(TO_INTERSTITIAL_START);
TOPON_ANE_FUNCTION(TO_INTERSTITIAL_IS_READY);
TOPON_ANE_FUNCTION(TO_INTERSTITIAL_SHOW);

#pragma mark - banner
TOPON_ANE_FUNCTION(TO_BANNER_START);
TOPON_ANE_FUNCTION(TO_SET_BANNER_ALIGN);
TOPON_ANE_FUNCTION(TO_BANNER_SHOW);
TOPON_ANE_FUNCTION(TO_BANNER_HIDE);
TOPON_ANE_FUNCTION(TO_BANNER_IS_READY);
TOPON_ANE_FUNCTION(TO_BANNER_REMOVE);

#pragma mark - nativeBanner
TOPON_ANE_FUNCTION(TO_NATIVE_BANNER_START);
TOPON_ANE_FUNCTION(TO_SET_NATIVE_BANNER_ALIGN);
TOPON_ANE_FUNCTION(TO_NATIVE_BANNER_SHOW);
TOPON_ANE_FUNCTION(TO_NATIVE_BANNER_HIDE);
TOPON_ANE_FUNCTION(TO_NATIVE_BANNER_IS_READY);
TOPON_ANE_FUNCTION(TO_NATIVE_BANNER_REMOVE);


#pragma mark - native
TOPON_ANE_FUNCTION(TO_NATIVE_START);
TOPON_ANE_FUNCTION(TO_NATIVE_IS_READY);
TOPON_ANE_FUNCTION(TO_NATIVE_SHOW);
TOPON_ANE_FUNCTION(TO_NATIVE_REMOVE);
TOPON_ANE_FUNCTION(TO_NATIVE_LAYOUT);

///开屏
TOPON_ANE_FUNCTION(TO_USER_PURCHASE);

///停止计时器
TOPON_ANE_FUNCTION(TO_STOP_DISPLAYLINK);

///临时方案
TOPON_ANE_FUNCTION(TO_IS_READY_IV);

TOPON_ANE_FUNCTION(TO_SET_LOG_ENABLE);





